# Generated by Django 2.0.7 on 2018-07-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20180730_2314'),
        ('items', '0004_auto_20180729_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='categories.Category'),
        ),
    ]
