# Generated by Django 2.0.7 on 2018-07-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20180729_2002'),
        ('categories', '0002_itemcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='ItemsCategory',
        ),
    ]
