# Generated by Django 2.0.7 on 2018-07-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180729_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemscategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='itemscategory',
            name='item',
        ),
        migrations.DeleteModel(
            name='ItemsCategory',
        ),
    ]
